const words = [
    { word: 'Apple', hint: 'A fruit' },
    { word: 'Banana', hint: 'A yellow fruit' },
    { word: 'Giraffe', hint: 'A tall animal' },
    { word: 'Elephant', hint: 'A large mammal with a trunk' },
    { word: 'Strawberry', hint: 'A red, juicy fruit' },
    { word: 'Keyboard', hint: 'A computer input device' },
    { word: 'Ocean', hint: 'A large body of water' },
    { word: 'Mountain', hint: 'A large natural elevation of earth' },
    { word: 'Pencil', hint: 'A tool used for writing' },
    { word: 'Penguin', hint: 'A flightless bird' },
    { word: 'Camera', hint: 'A device for taking photographs' },
    { word: 'Pizza', hint: 'A popular Italian dish' },
    { word: 'Laptop', hint: 'A portable computer' },
    { word: 'Tiger', hint: 'A large wild cat' },
    { word: 'Rainbow', hint: 'A multicolored arc in the sky' },
    { word: 'Carrot', hint: 'An orange vegetable' },
    { word: 'Guitar', hint: 'A stringed musical instrument' },
    { word: 'River', hint: 'A flowing body of water' },
    { word: 'Spider', hint: 'An eight-legged arachnid' },
    { word: 'Clock', hint: 'A device that tells time' },
    { word: 'Shark', hint: 'A large marine predator' },
    { word: 'Whale', hint: 'A giant marine mammal' },
    { word: 'Book', hint: 'A source of written knowledge' },
    { word: 'Candle', hint: 'A source of light with wax' },
    { word: 'Football', hint: 'A popular team sport' },
    { word: 'Bridge', hint: 'A structure that spans over water' },
    { word: 'Diamond', hint: 'A precious stone' },
    { word: 'Jellyfish', hint: 'A sea creature with tentacles' },
    { word: 'Turtle', hint: 'A reptile with a shell' },
    { word: 'Kangaroo', hint: 'An animal known for its hopping' },
    { word: 'Robot', hint: 'A machine capable of performing tasks' },
    { word: 'Chocolate', hint: 'A sweet treat made from cocoa' },
    { word: 'Iceberg', hint: 'A large floating mass of ice' },
    { word: 'Dragonfly', hint: 'An insect with transparent wings' },
    { word: 'Basketball', hint: 'A sport played with a hoop' },
    { word: 'Helicopter', hint: 'A flying vehicle with rotating blades' },
    { word: 'Volcano', hint: 'A mountain that can erupt' },
    { word: 'Honey', hint: 'A sweet substance made by bees' },
    { word: 'Eagle', hint: 'A bird of prey' },
    { word: 'Sunflower', hint: 'A tall yellow flower' },
    { word: 'Compass', hint: 'A tool used for navigation' },
    { word: 'Telescope', hint: 'A device for viewing distant objects' },
    { word: 'Chocolate', hint: 'A sweet treat made from cocoa' },
    { word: 'Squirrel', hint: 'A small tree-climbing animal' },
    { word: 'Windmill', hint: 'A structure that converts wind to energy' },
    { word: 'Sandwich', hint: 'Two slices of bread with filling' },
    { word: 'Octopus', hint: 'A sea creature with eight arms' },
    { word: 'Microscope', hint: 'A tool used to view small objects' },
    { word: 'Firetruck', hint: 'A vehicle used to fight fires' },
    { word: 'Airplane', hint: 'A flying vehicle' },
    { word: 'Bicycle', hint: 'A two-wheeled vehicle' }
];
